insert into public.topics (slug, title, track, position, blurb) values
('arrays-hashing','Arrays & Hashing','dsa',1,'Frequency maps, sets and the habit of trading memory for speed.'),
('two-pointers','Two Pointers','dsa',2,'Walk a sorted or symmetric structure from both ends.'),
('sliding-window','Sliding Window','dsa',3,'Maintain a moving range instead of recomputing it.'),
('stack','Stack','dsa',4,'Last in, first out: matching, monotonic stacks, expression parsing.'),
('binary-search','Binary Search','dsa',5,'Halve the search space, including on answers rather than arrays.'),
('linked-list','Linked List','dsa',6,'Pointer surgery, fast and slow pointers, dummy heads.'),
('trees','Trees','dsa',7,'Recursion on structure: DFS, BFS, BSTs.'),
('heap-priority-queue','Heap / Priority Queue','dsa',8,'Always know the min or max in O(log n).'),
('backtracking','Backtracking','dsa',9,'Build candidates step by step and undo the choice.'),
('tries','Tries','dsa',10,'Prefix trees for words and autocomplete.'),
('graphs','Graphs','dsa',11,'Grids, BFS/DFS, topological order, union-find.'),
('advanced-graphs','Advanced Graphs','dsa',12,'Shortest paths and minimum spanning trees.'),
('dp-1d','1-D Dynamic Programming','dsa',13,'Define the state, write the recurrence, then optimise.'),
('dp-2d','2-D Dynamic Programming','dsa',14,'Grids and two-sequence problems.'),
('greedy','Greedy','dsa',15,'Take the locally best choice and prove it holds.'),
('intervals','Intervals','dsa',16,'Sort by start, then merge or sweep.'),
('math-geometry','Math & Geometry','dsa',17,'Matrix tricks and number properties.'),
('bit-manipulation','Bit Manipulation','dsa',18,'XOR, masks and shifts.');

insert into public.problems (topic_id, title, url, platform, slug, difficulty, position)
select t.id, split_part(r.v, '|', 2), 'https://leetcode.com/problems/' || split_part(r.v, '|', 3) || '/', 'leetcode',
       split_part(r.v, '|', 3),
       case split_part(r.v, '|', 4) when 'e' then 'easy' when 'm' then 'medium' else 'hard' end,
       r.n
from unnest(array[
'arrays-hashing|Contains Duplicate|contains-duplicate|e',
'arrays-hashing|Valid Anagram|valid-anagram|e',
'arrays-hashing|Two Sum|two-sum|e',
'arrays-hashing|Group Anagrams|group-anagrams|m',
'arrays-hashing|Top K Frequent Elements|top-k-frequent-elements|m',
'arrays-hashing|Product of Array Except Self|product-of-array-except-self|m',
'arrays-hashing|Valid Sudoku|valid-sudoku|m',
'arrays-hashing|Longest Consecutive Sequence|longest-consecutive-sequence|m',
'two-pointers|Valid Palindrome|valid-palindrome|e',
'two-pointers|Two Sum II - Input Array Is Sorted|two-sum-ii-input-array-is-sorted|m',
'two-pointers|3Sum|3sum|m',
'two-pointers|Container With Most Water|container-with-most-water|m',
'two-pointers|Trapping Rain Water|trapping-rain-water|h',
'sliding-window|Best Time to Buy and Sell Stock|best-time-to-buy-and-sell-stock|e',
'sliding-window|Longest Substring Without Repeating Characters|longest-substring-without-repeating-characters|m',
'sliding-window|Longest Repeating Character Replacement|longest-repeating-character-replacement|m',
'sliding-window|Permutation in String|permutation-in-string|m',
'sliding-window|Minimum Window Substring|minimum-window-substring|h',
'sliding-window|Sliding Window Maximum|sliding-window-maximum|h',
'stack|Valid Parentheses|valid-parentheses|e',
'stack|Min Stack|min-stack|m',
'stack|Evaluate Reverse Polish Notation|evaluate-reverse-polish-notation|m',
'stack|Generate Parentheses|generate-parentheses|m',
'stack|Daily Temperatures|daily-temperatures|m',
'stack|Car Fleet|car-fleet|m',
'stack|Largest Rectangle in Histogram|largest-rectangle-in-histogram|h',
'binary-search|Binary Search|binary-search|e',
'binary-search|Search a 2D Matrix|search-a-2d-matrix|m',
'binary-search|Koko Eating Bananas|koko-eating-bananas|m',
'binary-search|Find Minimum in Rotated Sorted Array|find-minimum-in-rotated-sorted-array|m',
'binary-search|Search in Rotated Sorted Array|search-in-rotated-sorted-array|m',
'binary-search|Time Based Key-Value Store|time-based-key-value-store|m',
'binary-search|Median of Two Sorted Arrays|median-of-two-sorted-arrays|h',
'linked-list|Reverse Linked List|reverse-linked-list|e',
'linked-list|Merge Two Sorted Lists|merge-two-sorted-lists|e',
'linked-list|Linked List Cycle|linked-list-cycle|e',
'linked-list|Reorder List|reorder-list|m',
'linked-list|Remove Nth Node From End of List|remove-nth-node-from-end-of-list|m',
'linked-list|Copy List with Random Pointer|copy-list-with-random-pointer|m',
'linked-list|Add Two Numbers|add-two-numbers|m',
'linked-list|Find the Duplicate Number|find-the-duplicate-number|m',
'linked-list|LRU Cache|lru-cache|m',
'linked-list|Merge k Sorted Lists|merge-k-sorted-lists|h',
'linked-list|Reverse Nodes in k-Group|reverse-nodes-in-k-group|h',
'trees|Invert Binary Tree|invert-binary-tree|e',
'trees|Maximum Depth of Binary Tree|maximum-depth-of-binary-tree|e',
'trees|Diameter of Binary Tree|diameter-of-binary-tree|e',
'trees|Balanced Binary Tree|balanced-binary-tree|e',
'trees|Same Tree|same-tree|e',
'trees|Subtree of Another Tree|subtree-of-another-tree|e',
'trees|Lowest Common Ancestor of a Binary Search Tree|lowest-common-ancestor-of-a-binary-search-tree|m',
'trees|Binary Tree Level Order Traversal|binary-tree-level-order-traversal|m',
'trees|Binary Tree Right Side View|binary-tree-right-side-view|m',
'trees|Count Good Nodes in Binary Tree|count-good-nodes-in-binary-tree|m',
'trees|Validate Binary Search Tree|validate-binary-search-tree|m',
'trees|Kth Smallest Element in a BST|kth-smallest-element-in-a-bst|m',
'trees|Construct Binary Tree from Preorder and Inorder Traversal|construct-binary-tree-from-preorder-and-inorder-traversal|m',
'trees|Binary Tree Maximum Path Sum|binary-tree-maximum-path-sum|h',
'trees|Serialize and Deserialize Binary Tree|serialize-and-deserialize-binary-tree|h',
'heap-priority-queue|Kth Largest Element in a Stream|kth-largest-element-in-a-stream|e',
'heap-priority-queue|Last Stone Weight|last-stone-weight|e',
'heap-priority-queue|K Closest Points to Origin|k-closest-points-to-origin|m',
'heap-priority-queue|Kth Largest Element in an Array|kth-largest-element-in-an-array|m',
'heap-priority-queue|Task Scheduler|task-scheduler|m',
'heap-priority-queue|Design Twitter|design-twitter|m',
'heap-priority-queue|Find Median from Data Stream|find-median-from-data-stream|h',
'backtracking|Subsets|subsets|m',
'backtracking|Combination Sum|combination-sum|m',
'backtracking|Permutations|permutations|m',
'backtracking|Subsets II|subsets-ii|m',
'backtracking|Combination Sum II|combination-sum-ii|m',
'backtracking|Word Search|word-search|m',
'backtracking|Palindrome Partitioning|palindrome-partitioning|m',
'backtracking|Letter Combinations of a Phone Number|letter-combinations-of-a-phone-number|m',
'backtracking|N-Queens|n-queens|h',
'tries|Implement Trie (Prefix Tree)|implement-trie-prefix-tree|m',
'tries|Design Add and Search Words Data Structure|design-add-and-search-words-data-structure|m',
'tries|Word Search II|word-search-ii|h',
'graphs|Number of Islands|number-of-islands|m',
'graphs|Clone Graph|clone-graph|m',
'graphs|Max Area of Island|max-area-of-island|m',
'graphs|Pacific Atlantic Water Flow|pacific-atlantic-water-flow|m',
'graphs|Surrounded Regions|surrounded-regions|m',
'graphs|Rotting Oranges|rotting-oranges|m',
'graphs|Course Schedule|course-schedule|m',
'graphs|Course Schedule II|course-schedule-ii|m',
'graphs|Redundant Connection|redundant-connection|m',
'graphs|Word Ladder|word-ladder|h',
'advanced-graphs|Network Delay Time|network-delay-time|m',
'advanced-graphs|Cheapest Flights Within K Stops|cheapest-flights-within-k-stops|m',
'advanced-graphs|Min Cost to Connect All Points|min-cost-to-connect-all-points|m',
'advanced-graphs|Reconstruct Itinerary|reconstruct-itinerary|h',
'advanced-graphs|Swim in Rising Water|swim-in-rising-water|h',
'dp-1d|Climbing Stairs|climbing-stairs|e',
'dp-1d|Min Cost Climbing Stairs|min-cost-climbing-stairs|e',
'dp-1d|House Robber|house-robber|m',
'dp-1d|House Robber II|house-robber-ii|m',
'dp-1d|Longest Palindromic Substring|longest-palindromic-substring|m',
'dp-1d|Palindromic Substrings|palindromic-substrings|m',
'dp-1d|Decode Ways|decode-ways|m',
'dp-1d|Coin Change|coin-change|m',
'dp-1d|Maximum Product Subarray|maximum-product-subarray|m',
'dp-1d|Word Break|word-break|m',
'dp-1d|Longest Increasing Subsequence|longest-increasing-subsequence|m',
'dp-1d|Partition Equal Subset Sum|partition-equal-subset-sum|m',
'dp-2d|Unique Paths|unique-paths|m',
'dp-2d|Longest Common Subsequence|longest-common-subsequence|m',
'dp-2d|Best Time to Buy and Sell Stock with Cooldown|best-time-to-buy-and-sell-stock-with-cooldown|m',
'dp-2d|Coin Change II|coin-change-ii|m',
'dp-2d|Target Sum|target-sum|m',
'dp-2d|Interleaving String|interleaving-string|m',
'dp-2d|Edit Distance|edit-distance|m',
'dp-2d|Longest Increasing Path in a Matrix|longest-increasing-path-in-a-matrix|h',
'dp-2d|Distinct Subsequences|distinct-subsequences|h',
'dp-2d|Burst Balloons|burst-balloons|h',
'dp-2d|Regular Expression Matching|regular-expression-matching|h',
'greedy|Maximum Subarray|maximum-subarray|m',
'greedy|Jump Game|jump-game|m',
'greedy|Jump Game II|jump-game-ii|m',
'greedy|Gas Station|gas-station|m',
'greedy|Hand of Straights|hand-of-straights|m',
'greedy|Merge Triplets to Form Target Triplet|merge-triplets-to-form-target-triplet|m',
'greedy|Partition Labels|partition-labels|m',
'greedy|Valid Parenthesis String|valid-parenthesis-string|m',
'intervals|Insert Interval|insert-interval|m',
'intervals|Merge Intervals|merge-intervals|m',
'intervals|Non-overlapping Intervals|non-overlapping-intervals|m',
'intervals|Minimum Interval to Include Each Query|minimum-interval-to-include-each-query|h',
'math-geometry|Happy Number|happy-number|e',
'math-geometry|Plus One|plus-one|e',
'math-geometry|Rotate Image|rotate-image|m',
'math-geometry|Spiral Matrix|spiral-matrix|m',
'math-geometry|Set Matrix Zeroes|set-matrix-zeroes|m',
'math-geometry|Pow(x, n)|powx-n|m',
'math-geometry|Multiply Strings|multiply-strings|m',
'math-geometry|Detect Squares|detect-squares|m',
'bit-manipulation|Single Number|single-number|e',
'bit-manipulation|Number of 1 Bits|number-of-1-bits|e',
'bit-manipulation|Counting Bits|counting-bits|e',
'bit-manipulation|Reverse Bits|reverse-bits|e',
'bit-manipulation|Missing Number|missing-number|e',
'bit-manipulation|Sum of Two Integers|sum-of-two-integers|m',
'bit-manipulation|Reverse Integer|reverse-integer|m'
]) with ordinality as r(v, n)
join public.topics t on t.slug = split_part(r.v, '|', 1)
order by r.n;

-- position within a topic (ids follow the array order because of ORDER BY above)
update public.problems p set position = s.rn
from (select id, row_number() over (partition by topic_id order by id) as rn from public.problems) s
where s.id = p.id;
